### PR TITLE
Fix bug when calculating OVERNIGHT and TOM in calculateTenorDate

### PR DESCRIPTION
**Pull request by shaolang**
calculateTenorDate method in AbstractCurrencyDateCalculator adds one day to
to the expected dates for value Today and value Tomorrow.

### CODE REVIEW

**Comment by benoitx** [comment]
Sorry for the delay. Fix is very appreciated.

**Comment by shaolang** [comment]
sorry for commenting on this old thread: do you have near-term plans to release either a patch- or minor-release to Maven Central?

**Comment by benoitx** [comment]
Hi

Yep, I'd like to but the maven build is causing me some issues and I'm not
too sure how to fix it at the moment...

The steps to do a maven release are not obvious with Github, Sonatype and
Travis...

I'll investigate, any suggestions?

**Comment by shaolang** [comment]
I'm not sure what you mean by "not obvious with Github, Sonatype, and Travis." Was it easier on Sourceforge?

You may want to check out the [article at DZone](https://dzone.com/articles/how-to-create-and-release-a-jar-to-maven-central) for help.

Let me know how I could help too.

**Comment by benoitx** [comment]
It seems always difficult and brittle to do a release ie.:
* change the version
* build the website
* deploy to sonatype

I did it for Flatpack recently and it worked according to the
maven-notes.txt (checked in flatpack) but when I tried for ObjectLab Kit
that didn't work... Unfortunately, I am going to be away from a computer
for the next 4 days... but your help would be great to rationalise the
pom(s).xml and fully understand the mechanism better. Thanks!

**Comment by shaolang** [comment]
I've initiated pull request #21 to address the site generation problem.

**Pull request merged**
